### PR TITLE
Jbuilder

### PR DESCRIPTION
**Pull request by jaredly**
continuation of #30

### CODE REVIEW

**Comment by jaredly** [comment]
I think it leads to less confusion. Might has well have the directories have the same names as the compiled artifacts

**Comment by jaredly** [comment]
tbh I'd rather capitalize `Internal_lib` and all of the source files `M1.re` etc.

**Comment by jordwalke** [comment]
@jaredly If you prefer it, you can capitalize the files if you like - we could also setup a case sensitive travis build to let us know if that introduces any issues.

I think the underscores are a little more unfamiliar to JS developers though. Is there a way to allow people to consume the result of this as `ReasonNativeProject.InnerModules`? Is there some limitation in jBuilder?

**Comment by jaredly** [comment]
oh for sure! I was just converting from kebab to underscores, I'm totally fine with camel

**Comment by jordwalke** [comment]
Nice! I'll just wait until the CI passes then merge!

**Comment by jordwalke** [comment]
Happy to merge, but CI is not happy for some reason. Do you know what's up?

**Comment by jaredly** [comment]
oh funny, looks like there some duplication between `travis.yml` and `test-with-version`

**Comment by jordwalke** [comment]
Very good! Thank you @jaredly. Thank you @rgrinberg! This is a massive improvement.

**Comment by kennetpostigo** [comment]
Does the readme of the project need to be updated with the move to JBuilder?

**Comment by jordwalke** [comment]
yes! Do you feel like helping to document it?
( @jaredly might have suggestions for going beyond basic instructions but feel free to send PRs for ideas )

**Pull request merged**
